### ISSUE TITLE
Makefile.workspace unusable (likely) due to a glitch

### ISSUE THREAD

**Issue by spsquared** [ev3rt-git/ev3rt-hrp2-sdk#12]
I was following the [getting started](https://ev3rt-git.github.io/get_started/) page on the [github.io](https://ev3rt-git.github.io/get_started/) website, and when I ran
`make app=helloev3`
it immediately spat out
`Makefile:1: *** missing separator.  Stop.`
I looked into the makefile and it lead me to the first line of makefile.workspace (in the "common" folder), which was a comment. The internet says that makefiles do things with spaces and tabs, and that could be the problem. I tried looking at the first non-comment line and didn't fix it. I removed it and recloned it. I uninstalled everything and reinstalled everything. I tried on a different computer. I conclude that the problem is a glitch/bug in the way the makefile is run.

**Comment by JarekParal** [comment]
@definitely-nobody-is-here You should also check CR and LF (new line convention). There could be an issue with Linux (just LF) and Windows (CR + LF). If you clone git repository in Windows and make build with 
Cygwin it could cause some problems. And the second thing, there are symlinks that have to be enabled in Git setting (as they are used in this repository).

**Comment by spsquared** [comment]
That did not appear to work. The Git setting should be enabled (unless it doesn't register) and I cloned it on a linux machine once. I'll try to use an older version that I already have.
