### ISSUE TITLE
Turn off Bluetooth

### ISSUE THREAD

**Issue by timmmerlan** [ev3rt-git/ev3rt-hrp2-sdk#6]
Hello,
is there any way to turn off bluetooth with an entry in the rc.conf.ini or by changing some lines in the source code of the image?
Thank you in advance for your answer!
Tim

**Comment by YixiaoLi** [comment]
Hello,
I have added an entry to turn off Bluetooth (also updated FAQ in http://ev3rt-git.github.io/documents/).
Please clone the latest source from https://github.com/ev3rt-git/ev3rt-hrp2 and rebuild uImage file.
Hope it could help you.

Yixiao Li

**Comment by timmmerlan** [comment]
Hi,
thank you fpr the update! I tried to download it and compile an image according to those instructions: http://ev3rt-git.github.io/get_started/
At step 3 at the make-command I get the following error:
../../target/ev3_gcc/drivers/bluetooth/include/bluetooth_dri.h:3:10: fatal error: btstack-interface.h: No such file or directory #include "btstack-interface.h"
Does this have to do with the change in the source code?
Thank you in advance for your help!
Tim

**Comment by YixiaoLi** [comment]
Hi,
'btstack-interface.h' should be under 'ev3rt-hrp2/modules/btstack/platforms/ev3rt/' if all required files are downloaded by following step 1.
Please try to download again if that file doesn't exist.
Yixiao Li

**Comment by timmmerlan** [comment]
Hi,
thank you, we now found the file! Unfortunately, we still get an error during compiling :-(
`../loader/zmodem/src/zmodem-newlib.c: In function '_write_r':
../loader/zmodem/src/zmodem-newlib.c:25:5: warning: implicit declaration of function 'extsvc_newlib_write_r' [-Wimplicit-function-declaration]
     extsvc_newlib_write_r(reent, fd, buf, cnt, NULL, TDOM_KERNEL);
     ^~~~~~~~~~~~~~~~~~~~~
  CC      kernel_cfg.c
  CC      kernel_mem2.c
  LINK    cfg2_out
cfg:cfg2_out.tf:3: error: syntax error
cfg: fatal error
make[1]: *** [kernel_mem3.c] Error 1
Makefile:40: recipe for target 'app' failed
make: *** [app] Error 2`

Furthermore, we got some warnings during the make command in the cfg folder:
`factory.cpp: In function ‘void toppers::oil::{anonymous}::set_object_vars(const cfg_obj_map&, toppers::macro_processor&)’:
factory.cpp:164:60: warning: format ‘%llx’ expects argument of type ‘long long unsigned int*’, but argument 3 has type ‘uint64_t* {aka long unsigned int*}’ [-Wformat=]
                 sscanf(value_str.c_str() , "0x%llx" , &temp);
                                                            ^
factory.cpp:171:60: warning: format ‘%llx’ expects argument of type ‘long long unsigned int*’, but argument 3 has type ‘uint64_t* {aka long unsigned int*}’ [-Wformat=]
                 sscanf(value_str.c_str() , "0X%llx" , &temp);
                                                            ^
factory.cpp:198:60: warning: format ‘%llx’ expects argument of type ‘long long unsigned int*’, but argument 3 has type ‘int64_t* {aka long int*}’ [-Wformat=]
                 sscanf(value_str.c_str() , "0x%llx" , &temp);
                                                            ^
factory.cpp:205:60: warning: format ‘%llx’ expects argument of type ‘long long unsigned int*’, but argument 3 has type ‘int64_t* {aka long int*}’ [-Wformat=]
                 sscanf(value_str.c_str() , "0X%llx" , &temp);
                                                            ^
g++ -O2   -I/usr/local/include/boost-1_42_0 -I../..  -c -o oil_object.o oil_object.cpp
oil_object.cpp: In member function ‘virtual bool toppers::oil::oil_implementation::parameter_int_impl::validate_object_parameter(toppers::oil::oil_definition::object_parameter_def*)’:
oil_object.cpp:319:63: warning: format ‘%llx’ expects argument of type ‘long long unsigned int*’, but argument 3 has type ‘int64_t* {aka long int*}’ [-Wformat=]
      (void)sscanf(obj->get_value().c_str() , "0x%llx" , &value);
                                                               ^
oil_object.cpp:325:63: warning: format ‘%llx’ expects argument of type ‘long long unsigned int*’, but argument 3 has type ‘int64_t* {aka long int*}’ [-Wformat=]
      (void)sscanf(obj->get_value().c_str() , "0X%llx" , &value);
                                                               ^
oil_object.cpp: In member function ‘virtual bool toppers::oil::oil_implementation::parameter_uint_impl::validate_object_parameter(toppers::oil::oil_definition::object_parameter_def*)’:
oil_object.cpp:398:63: warning: format ‘%llx’ expects argument of type ‘long long unsigned int*’, but argument 3 has type ‘uint64_t* {aka long unsigned int*}’ [-Wformat=]
      (void)sscanf(obj->get_value().c_str() , "0x%llx" , &value);
                                                               ^
oil_object.cpp:404:63: warning: format ‘%llx’ expects argument of type ‘long long unsigned int*’, but argument 3 has type ‘uint64_t* {aka long unsigned int*}’ [-Wformat=]
      (void)sscanf(obj->get_value().c_str() , "0X%llx" , &value);`
Could you help us with that issue? Thank you in advance for your continuous support!
Tim
